#!/bin/sh
#
# Ian - 16/11/2011
# /etc/init.d/newznab: start and stop the newznab update script
#
# run update-rc.d newznab_ubuntu.sh defaults


### BEGIN INIT INFO
# Provides:          Newznab
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start newznab at boot time
# Description:       Enable newznab service provided by daemon.
### END INIT INFO


# Newznab variables 
NN_PATH="/var/www/newznab/misc/update_scripts"
NN_MISC="/var/www/newznab/misc/testing"
NN_BINUP="update_binaries.php"
NN_BINUPT="update_binaries_threaded.php"
NN_RELUP="update_releases.php"
NN_OPDB="optimise_db.php"
NN_TVS="update_tvschedule.php"
NN_TTR="update_theaters.php"
NN_PRE="update_predb.php"
NN_SLEEP_TIME="60" # in seconds . 10sec is good for 100s of groups. 600sec might be a good start for fewer.
NN_PID_PATH="/var/run/" 

NN_PARSE="update_parsing.php"
NN_DELREL="deletereleases.php"

PROWL_PATH="/var/www/newznab/misc/thirdparty/php-prowl-cli"
NN_PROWL="cli_prowl.php"

SPHINX_PATH = "/var/www/newznab/misc/sphinx"
SPHINX_SCRIPT = "nnindexer.php"

PIDFILE="newznab_binup.pid"

test -f /lib/lsb/init-functions || exit 1
. /lib/lsb/init-functions



case "$1" in
  start)
  [ -f ${NN_PID_PATH}${PIDFILE} ] && { echo "$0 is already ruNNing."; false; }
        echo -n "Starting Newznab binaries update"
        cd ${NN_PATH}
        (while (true);do cd ${NN_PATH} && php ${NN_BINUPT}  2>&1 > /var/log/nn_log.log && php ${NN_RELUP}  2>&1 >> /var/log/nn_log.log && php ${NN_PRE}  2>&1 >> /var/log/nn_log.log && php ${NN_TVS}  2>&1 >> /var/log/nn_log.log && php ${NN_TTR}  2>&1 >> /var/log/nn_log.log && php ${NN_OPDB}  2>&1 >> /var/log/nn_log.log && php ${NN_MISC}/${NN_PARSE} 2>&1 >> /var/log/nn_log.log && php ${PROWL_PATH}/${NN_PROWL} "Processing Complete" "All Steps Complete, Taking a 1 minute Break" "0" "cxbin.gwelsted.com"; sleep ${NN_SLEEP_TIME} ;done) &
        PID=`echo $!`
        echo $PID > ${NN_PID_PATH}${PIDFILE}
        ;;
  stop)
        echo -n "Stopping Newznab binaries update"
        kill -9 `cat ${NN_PID_PATH}${PIDFILE}`
        ;;

  *)
        echo "Usage: $0 [start|stop]"
        exit 1
esac

